### ISSUE TITLE
pvacseq run MHCII break off with KeyError: 'seq_num'

### ISSUE THREAD

**Issue by huangxiaogua** [griffithlab/pVACtools#109]
hello,
When I used pvacseq 4.0.9 to run mouse MHCII prediction,the program broke off while Running IEDB.Here is my input command

`pvacseq run /home/jm/DATA/vepout_files/mC0001-3vepout.vcf mc0001 H2-IAb NNalign /home/jm/DATA/mc0001_mhcII2 --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files`
following are the output of my terminal
`Executing MHC Class II predictions
Converting VCF to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-400
Splitting TSV into smaller chunks - Entries 401-500
Splitting TSV into smaller chunks - Entries 501-600
Splitting TSV into smaller chunks - Entries 601-700
Splitting TSV into smaller chunks - Entries 701-800
Splitting TSV into smaller chunks - Entries 801-900
Splitting TSV into smaller chunks - Entries 901-1000
Splitting TSV into smaller chunks - Entries 1001-1100
Splitting TSV into smaller chunks - Entries 1101-1200
Splitting TSV into smaller chunks - Entries 1201-1300
Splitting TSV into smaller chunks - Entries 1301-1400
...........

Completed
Processing entries for Allele H2-IAb - Entries 5601-5800
Running IEDB on Allele H2-IAb with Method NNalign - Entries 5601-5800
Completed
Parsing IEDB Output for Allele H2-IAb - Entries 5601-5800
Traceback (most recent call last):
  File "/home/jm/miniconda2/envs/env_name/bin/pvacseq", line 6, in <module>
    sys.exit(pvacseq.pvacseq.main())
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/main.py", line 313, in main
    pipeline.execute()
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/pipeline.py", line 300, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/pipeline.py", line 548, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/parse_output.py", line 461, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/parse_output.py", line 370, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/home/jm/miniconda2/envs/env_name/lib/python3.6/site-packages/pvacseq/lib/parse_output.py", line 258, in parse_iedb_file
    protein_label  = int(line['seq_num'])
KeyError: 'seq_num'`

Can you find the  wrong point? Thank you.

**Comment by susannasiebert** [comment]
Can you check the file `/home/jm/DATA/mc0001_mhcII2/MHC_Class_II/tmp/mc0001.nn_align.H2-IAb.tsv_5601-5800`. Is it empty? If so, it means that for some reason IEDB ran for this chunk successfully but didn't return an output, which is odd. Can you try removing that file and rerunning the exact same command again (without removing any of the existing output files)? It should skip all the processing already done and resume at the prediction step for that chunk.

If this doesn't help, would you be able to share the associated fasta? The file would be at `/home/jm/DATA/mc0001_mhcII2/MHC_Class_II/tmp/mc0001_21.fa.split_5601-5800`.

I also suggest to use the pvactools package instead of the old pvacseq package. The pvacseq package has been deprecated and replaced by pvactools. You can install it by running `pip uninstall pvacseq` and then `pip install pvactools`. Your command will stay the same. 

Lastly, since you are running a rather large amount of variants, I would recommend to use a local IEDB installation. Please see http://pvactools.readthedocs.io/en/latest/install.html#mhc-class-ii for installation instructions.

**Comment by huangxiaogua** [comment]
I followed your advice that installed pvactools, it can be run normally. Thank you very much!
