### ISSUE TITLE
MHC allele supported by the original prediction method, but not recognized by pvacseq

### ISSUE THREAD

**Issue by luyh-xp** [griffithlab/pVACtools#1146]
I'm trying to use NetMHCIIpan to predict epitope binding to a mouse class II allele, H2-IEd. Output of `pvacseq valid_algorithms -a H2-IEd` suggests that it is not supported by NetMHCIIpan, yet it is in the list of supported alleles on NetMHCIIpan website. 

Turns out if I add H2-IEd to `iedb/mhc_ii/methods/allele-info/allele_info/pickles/mhcii_info_dict.p` and `pvactools/tools/pvacseq/iedb_alleles/class_ii/NetMHCIIpan.tsv`, pvacseq is indeed able to generate NetMHCIIpan prediction for this allele. So I wonder if there is any particular reason that this allele is disabled in pvacseq configuration files?

**Comment by susannasiebert** [comment]
It seems you are right. We got our list from https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.0/alleles_name.list. Can you please let me know which list you were using so I can double check that we are supporting all possible alleles.

**Comment by luyh-xp** [comment]
@susannasiebert I was using [https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.3/alleles_name.list](https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.3/alleles_name.list). I was initially concerned that this allele might be left out due to its predictions being problematic, but I saw your recent commit with the updated list so my question is answered. Thanks for taking care of this!

**Comment by susannasiebert** [comment]
That looks like a newer version than what is supported in IEDB (4.0 and 4.1). I will do some more research into the different versions and test which alleles actually work with IEDB. The IEDB lists aren’t always up date it looks like.

I’m not sure why this allele wasn’t formally listed in the original 4.0/4.1 versions since it still seems to work. I don’t have any information about how reliable the predictions are under the older netmhciipan versions, unfortunately.

**Comment by susannasiebert** [comment]
I apologize for the delay. The latest version of pVACtools (5.0.0) adds support for these alleles.
