### ISSUE TITLE
BigMHC and DeepImmuno future support

### ISSUE THREAD

**Issue by Stikus** [griffithlab/pVACtools#1151]
Hello @susannasiebert, thanks for great tool as always.

We recently discovered, that you have support for [BigMHC](https://github.com/KarchinLab/bigmhc) and [DeepImmuno](https://github.com/frankligy/DeepImmuno), but with [your custom installation](https://github.com/griffithlab/pVACtools/issues/1119#issuecomment-2191709127). Do you plan to upgrade your forks accordingly with original repos?

### About BigMHC:

For now, https://github.com/griffithlab/bigmhc is [10 commits ahead of](https://github.com/griffithlab/bigmhc/compare/KarchinLab%3Abigmhc%3Amaster...master), [4 commits behind](https://github.com/griffithlab/bigmhc/compare/master...KarchinLab%3Abigmhc%3Amaster) https://github.com/KarchinLab/bigmhc.

I've asked about it in https://github.com/KarchinLab/bigmhc/issues/6#issuecomment-2348968987, but no answer there, that's why I've created this issue.

Also, I've found merged PR https://github.com/KarchinLab/bigmhc/pull/7, but there are no setup.py in master branch now:
![image](https://github.com/user-attachments/assets/940b2765-46ab-4446-b47f-c49bfcbb322e)

And commit does not belong to any branch:
![image](https://github.com/user-attachments/assets/e15321be-6436-46ee-b1ab-bb0ddc4d5b79)

### About DeepImmuno:

Your fork is ahead and don't have any merge problems:
![image](https://github.com/user-attachments/assets/69c15338-a9a9-400c-bcdc-93e8c01d554d)

Do you plan to created PR for original repo?

---
BTW: Last time you said that TF version [should be pinned](https://github.com/griffithlab/pVACtools/issues/1084#issuecomment-2000228235) for pVACtools, but I don't see any pin in https://github.com/griffithlab/pVACtools/blob/master/setup.py/ Is in intended?

**Comment by serge2016** [comment]
Dear @susannasiebert, help us, please.

**Comment by susannasiebert** [comment]
My apologies for not replying sooner. Thank you for bringing this to our attention. I plan on updating our forks for both tools to the latest when I have some time for it. I'll let you know when that is completed.

**Comment by Stikus** [comment]
@susannasiebert Thanks for answer. So we should use your forks, you don't have plans to merge needed files/patches to main repos, correct?

**Comment by susannasiebert** [comment]
The difference between our forks and the main repos is only the ability to install the tools via pip, which makes using the algorithms from within pVACtools easier since pVACtools won't have to manage user's installation paths for these tools. As such, we intend to have our fork be functionally up to date with the main repos. If we were to discover any bugs, we'd make PRs for any fixes back to the main repo. 

As you have discovered, we tried making a PR for our "installation" feature back to BigMHC but they had to revert that PR. It's still in the plans to merge this functionality back into BigMHC at some point but it has been on the lower end of our priority list.
