### ISSUE TITLE
Help with MT-WT epitope match for inframe mutations

### ISSUE THREAD

**Issue by KhacDuyNguyen0** [griffithlab/pVACtools#1152]
Dear the authors,
I appriciate your workings to produce such a useful tool.

During the analysis, I identified a case involving an inframe insertion variant in the PIK3R1 gene at position 454, where T changes to TQFQEKS.
For more details,
- The WildtypeNmer: IEAVGKKLHEYN**T**QFQEKSREYDRL
- The Mutant Nmer:   IEAVGKKLHEYN**TQFQEKS**QFQEKSREYDRL

I understand that the matched wildtype epitope should share at least half of its length with the mutant epitope. For the mutant epitope FQEKSQFQE, I believe that FQEKSREYD would be an appropriate matched wildtype epitope, but the algorithm selected (NA) for this case. Similar issues appear with other mutant epitopes shown in the picture below.
![image](https://github.com/user-attachments/assets/5807da90-9fbc-4151-807b-4ff39f7c7c4c)

Another similar case occurs with mutations in the NCOR2 gene at position 1833-1834, where mutant and wildtype nmer as follows:
- The WildtypeNmer: EHAPIWRPGTEQSSGSSGGGGGSS
- The Mutant Nmer:   EHAPIWRPGTEQSSGSSGSSGGGGGSS
There are no matched wildtype epitopes for the following mutant epitopes GSSGSSGGG, SGSSGSSGG, SSGSSGSSG

 I would like to know the reasons and the pairing rules for such cases. Thank you in advance.
 
Best regards,
Duy

**Comment by susannasiebert** [comment]
This is an interesting case. I agree that I would expect these to match as you describe them. There might be a bug in our logic. Would you be able to share a VCF file with just these two variants in them so that I can try to debug in further on my end?

**Comment by KhacDuyNguyen0** [comment]
I am sorry for late response, here are my VCF files for these two mutations.
[inframe_mutations.zip](https://github.com/user-attachments/files/17144507/inframe_mutations.zip)

**Comment by susannasiebert** [comment]
A short update: I found the reason for this behavior. When we create the fasta file for making binding predictions, we only include n-1 flanking amino acids so that each n-length substring of the peptide overlaps the mutation position. However, with these particular examples, the insertion is actually a duplication of a longer region and the presumed mutation position `T` is not where the mutated amino acids start (which is at the end of the duplicated region). So not enough flanking amino acids were included in the fasta file pVACseq creates. You can see this reflected by looking at the .fasta file in the MHC_Class_I subfolder of your run. I'm working on fixing this error by including a longer subsequence for the WT of inframe insertions to account for duplicating insertions.

**Comment by KhacDuyNguyen0** [comment]
Thank you so much for your support.

**Comment by susannasiebert** [comment]
I apologize for the delay but this issue is resolved in the newest version of pVACtools, 5.0.0.
