### ISSUE TITLE
Indels processing

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVACtools#120]
Hi guys,
Wildtype and Downstream plugins not able to annotated GATK indels vcf file. Amino acid sequences were not generated in VEP processing. Do i need to change any parameter here?

**Comment by susannasiebert** [comment]
What parameters did you use to annotate your VCF with VEP? Maybe paste the whole VEP command. Most likely the Downstream and Wildtype plugins were not found in the VEP plugins directory.

**Comment by venkataddala** [comment]
VEP command:

variant_effect_predictor.pl -i Indel_GATK_Tumor.vcf --output_file VEP_Indel.vcf --vcf --symbol --terms SO  --dir /reference/software/vep  --symbol --dir_plugins /mnt/lustre/reference/software/vep/Plugins --plugin Downstream --plugin Wildtype --pick --coding_only --offlice GRCh37

**Comment by susannasiebert** [comment]
Interesting, what is the CSQ header in your annotated indels VCF?

**Comment by venkataddala** [comment]
INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|DownstreamProtein|ProteinLengthChange">

**Comment by venkataddala** [comment]
Nope, Wildtype plugin is there in it's path. I have no problem with missense variants. stuck with indels

**Comment by susannasiebert** [comment]
I would suggest checking the VEP annotation log to see if it throws an warning about the Wildtype plugin. I'm not sure why it wouldn't annotate it. The fact that the WildtypeProtein field isn't in the header shows me that it isn't run at all, which in my experience only happens when it can't find the plugin. You might also want to check the VEP annotation log to see if it throws an warning about the Wildtype plugin. If the log don't contain any warnings, I suggest putting in a ticket with Ensembl.

**Comment by susannasiebert** [comment]
What do the logs say about the Wildtype plugin? It should at least mention that it is trying to run it. Can you please post more detail or I won't be able to help you with your issue. If you could post an example of a log file, that would be useful.

Can you upgrade VEP to the latest version, like suggested in  Ensembl/ensembl-vep#153, and try to reannotate your files??

**Comment by venkataddala** [comment]
Figured out with VEP version, annotating successfully, But when i ran pvaseq tsv file missing INDELS into input, throwing this warning and continues with only missense variants.

Executing MHC Class I predictions
Converting .vcf to TSV
Allele number not found in list of alleles
Allele number not found in list of alleles
Allele number not found in list of alleles
Allele number not found in list of alleles
Allele number not found in list of alleles
Completed
Splitting TSV into smaller chunks
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-132
Completed
Processing entries for Allele HLA-A*02:01 and Epitope Length 9 - Entries 1-132
Running IEDB on Allele HLA-A*02:01 and Epitope Length 9 with Method NetMHCpan - Entries 1-132

**Comment by susannasiebert** [comment]
Can you please post an example indel VCF entry that gets filtered out as well as the CSQ header from the VCF?

**Comment by venkataddala** [comment]
[25_test.vcf.gz](https://github.com/griffithlab/pVACtools/files/2007436/25_test.vcf.gz)

Check this one

**Comment by susannasiebert** [comment]
None of the indels in your VCF are annotated by VEP as a `frameshift_variant`, `inframe_insertion`, or `inframe_deletion`, which are the only three indel types supported by pVACseq.

**Comment by venkataddala** [comment]
This file has inframe_deletion 
[10ACC_VEP_Fil.vcf.gz](https://github.com/griffithlab/pVACtools/files/2011222/10ACC_VEP_Fil.vcf.gz)

**Comment by venkataddala** [comment]
This one has frameshift_variant and deletions. please have a look. Thanks for help!
[Indel_filtered.vcf.gz](https://github.com/griffithlab/pVACtools/files/2011317/Indel_filtered.vcf.gz)

**Comment by susannasiebert** [comment]
I see a couple of things going on here where VEP seems to have changed their output format and it's different from what pVACseq is expecting.
(1) the Allele field in the CSQ entries for these indels is the literal string `deletion` instead of the actual alt allele. pVACseq uses this field to find the appropriate CSQ entries for each alternate allele, since in a multi-alt site there would be CSQ entries for each alternate allele. Right now pVACseq isn't able to find matching CSQ entries in your VCF because of that.
(2) Once (1) is resolved, the Consequence string format in the CSQ entries has changed as well. Right now pVACseq expects multiple entries in the Consequence field to be separated by a `&`. In your VCF, they are separated by a `.`.  pVACseq will split on the delimiter and check each consequence individual for supported consequence types instead of doing a fuzzy match on the whole consequence string. Because of this, pVACseq doesn't detect the `frameshift_deletion` or `inframe_deletion` consequences. 

I'm not sure if these formatting changes are because of the version of VEP being used or if it's because of how VEP was run. Either way, I'm happy to add support for this new format. Do you happen to have any examples for an inframe_insertion? All the examples I'm seeing are for deletions and I would like to make sure we parse all types of variants correctly in the new format.

Unfortunately, I will leave on vacation for two weeks on Friday. It's unlikely that a new release will be ready by then. I will work on a pull request tomorrow and am happy to give you instructions on how to install pVACtools directly from a GitHub branch so that you can try out the bugfix until it is release into production.

**Comment by venkataddala** [comment]
Here is what i have done so far, annotated with VEP91 and filtered variants with filter < vep.pl  --filter "consequence is frameshift_variant or consequence is inframe_deletion or consequence is inframe_insertion" > 
[Deletion_FramshiftVariant.vcf.gz](https://github.com/griffithlab/pVACtools/files/2011789/Deletion_FramshiftVariant.vcf.gz)
This one has deletions and frameshift. Please check this entries

**Comment by susannasiebert** [comment]
Ok, let me know if you encounter any cases like this for an `inframe_insertion`. For now I will add support for this new format for `inframe_deletion` and `frameshift_variant`.

**Comment by susannasiebert** [comment]
For the Indel_filtered.vcf.gz file I'm also running into the problem where the frameshift variants do not actually have any contents for the DownstreamProtein sequence field. The other variants don't have any contents for the Amino_acids field. This causes downstream errors. You might want to try to re-annotate it with the same workflow you used to create Deletion_FramshiftVariant.vcf.gz. That file doesn't have the same problems. I'm still working on creating a PR to fix some of the issues you are seeing and add more warning messages when these variants are skipped because of problems with the DownstreamProtein and Amino_acids fields.

**Comment by susannasiebert** [comment]
I made a pull request to address some of these problems you are seeing (#129). You can install pVACtools from the branch by running `pip install -e git+git://github.com/griffithlab/pVACtools@vep_formats#egg=pvactool`. You might need to uninstall your current version of pVACtools first (`pip uninstall pvactools`) to avoid conflicts.

**Comment by susannasiebert** [comment]
I just made a new release (version 1.0.6) that incorporates this hotfix.
