### ISSUE TITLE
pVACvector - list of candidates

### ISSUE THREAD

**Issue by sbwiecko** [griffithlab/pVACtools#216]
* pvactools version:
1.1.1
* Python version:
3.5.6
* Operating System:
Ubuntu on Windows 10
**Describe the bug**

This is not a bug but a suggestion for improvement.
We would like to test different candidates, not the only one provided by pVACvector.
Is there any parameter we could use to limit the number of candidates, i.e. different strings-of-beads with reasonable final score, so that we could test them in vitro and in vivo?
I believe the process test many combinations, so that we would like to see more of them, not only one.
Thank you for your great work!

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
The log that gets written to standard out
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**

**Comment by chrisamiller** [comment]
The process uses simulated annealing to converge upon a near optimal score.  You're right that many (but definitely not all) different arrangements are tested, but extracting them would require some rewriting of that module to store multiple states.  In the interest of gathering info before committing to rewriting anything: What number of arrangements would you like to see? If we choose just those encountered that exceed a given score, there will likely be tens of thousands of potential rearrangements (most minor variations of each other), and the list will not be completely comprehensive, since simulated annealing is not an exhaustive search. I expect that if we chose just the top N states, they're going to be very minor rearrangements of the same peptide ordering (i.e. only peptides N and M will be swapped)  How different does an ordering need to be to warrant investigation in your mind?

**Comment by tryptofan68** [comment]
Thanks for clarification. I understand the point. We would be interested for example, at the n=2-5 most different sequences within the same range of score, or at least above a threshold/percentile of the optimal score. This is the kind of numbers we are technically able to test in vitro and in vivo.

Ideally, if I have 4 epitopes x1 to x4, and pVACvector returns the optimal sequence x1-x2-x3-AAY-x4, I would like to test another 'good' sequence but with the order of the epitopes as different as possible from the optimal string, e.g. x2-x4-HH-x3-x1, but not x1-x2-x3-x4.

**Comment by chrisamiller** [comment]
Thanks for the feedback - it's a good idea. Can't promise anything immediate, but we'll add this to our development queue
