### ISSUE TITLE
Create an option that allows user to provide FASTA file as starting input

### ISSUE THREAD

**Issue by CodyRamirez** [griffithlab/pVACtools#299]
I would like to be able to provide pVACSeq with a FASTA file as input instead of an annotated VCF.

**Comment by malachig** [comment]
High level use cases:
- Support CDR sequences as input (for T and B cell malignancies)
- Support tumor associated antigens and Cancer/testis (CT) antigens

It could also provide interim support of alternative isoform derived antigens and an alternative workflow for RNA fusion associated antigens.

**Comment by susannasiebert** [comment]
From today's meeting:
- This should be a new tool (e.g., pVACbind?) because the FASTA would not contain matched mutant and wildtype epitope sequences so the downstream processing is substantially different from pVACseq.
- The output would be more bare bone since we don't have any of the normal variant information. e.g., positions, gene, transcript, vafs, depths, etc etc
- We might want to be able to add expression data so we should think about how that would be inputted to the new pipeline
- We can only run some of the filters: binding affinity (no fold change), top score filter 
- We can still run stability and cleavage site predictions
- We should see if we can create a condensed report although the score would not contain all four criteria
