### ISSUE TITLE
Run pVAC-Seq without conda

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVACtools#357]
Hello again!
For our purposes we have to run pVAC-Seq over Ubuntu 14.04.
We have both python2.7 and python3.6 installed.
python3.7 is not acceptable due to tensorflow issues: for our hardware we can use only tensorflow==1.5.0 and it doesn't support python3.7, only 3.6 and earlier: https://pypi.org/project/tensorflow/1.5.0/#files.

How can I ask pVAC-Seq not to use conda to run local IEDB?

**Comment by susannasiebert** [comment]
Unfortunately, it's not possible to run pVACseq with a local IEDB installation and without conda. IEDB is written in python 2.7 and expects that the be the default python while pVACtools is written in python 3.5 and expects that the be the default python. Conda is the most reliable way we've found to resolve those conflicting dependencies.

**Comment by serge2016** [comment]
It's definitely possible!
The only thing needed is both pythons in the system! I have created Dockerfile with the installation instructions starting from ubuntu:14.04 without conda where pvacseq works! It's ugly right now, but it shows that it's possible:
[Dockerfile.zip](https://github.com/griffithlab/pVACtools/files/3064195/Dockerfile.zip)

**Comment by susannasiebert** [comment]
What I meant to express with "it's not possible" is to say that the current implementation doesn't support it. We have no plans to move away from the current implementation as we've found having  both python2 and python3 installed at the same time to be highly problematic. We usually run into problems with certain scripts expecting the default python to be a different one than what it is written for, thus causing syntax errors.

I had a look at your Dockerfile and I'm not sure why you are using the outdated pVAC-Seq repository. 
pVACseq has been moved to the pVACtools suite. The repository you are using is no longer supported and is missing a host of new features we've added since moving pVACseq to pVACtools. Please use pVACtools and the `pvactools` package instead. We also provide our own Docker image at `griffithlab:pVACtools`. It already comes with IEDB preinstalled as well.

**Comment by serge2016** [comment]
@susannasiebert, sorry, my Dockerfile is not clean yet. I use `pip install pvactools`, the old pvacseq repo is commented.
I can't use your docker image due to issues with tenserflow. More over we need it to be based on ubuntu:14.04. I can't install pvactools together with tenserflow==1.5 (the only one that fits our hardware) automatically, so I'm trying to install differently.

These commands allow me to run pvacseq without conda:
```
sed -i -e '/^    if args.iedb_install_directory:$/,+1 {s/^\(.*\)$/#\1/}' /usr/local/lib/python3.6/dist-packages/tools/pvacseq/run.py
sed -i -e '/pvactools_py27/s/source activate pvactools_py27; //' /usr/local/lib/python3.6/dist-packages/lib/prediction_class.py
```

I hope you could add some kind of a flag that allows not to run conda inside pvacseq (that requires system python be 2.7)... I think I am not the only one who will benefit of it.

**Comment by susannasiebert** [comment]
The upcoming version 1.3.6 will pin tensorflow to version 1.5.0. You can also base your Dockerfile on ours and overwrite tensorflow in it. If you need to write your own, since you require Ubuntu, I don't see a reason why you can't install conda in it. Otherwise, the solution you've come up with seems to work for you.

I'm sorry but we won't start supporting these different ways that people may or may not install python locally. Once we start supporting it for you it's a rabbit whole of folks who have things set up slightly differently and need special handling for it. This will far outweigh our ability to provide user support.
