### ISSUE TITLE
Inframe deletions not being processed by pVACseq

### ISSUE THREAD

**Issue by csweeney225** [griffithlab/pVACtools#431]
* pvactools version: 1.4.2
* Python version: 3.6.7
* Operating System: Linux

**Describe the bug**
I am trying to run pvacseq to predict MHC class I and class II binding affinities. I have created my vcf files using the hg38 assembly and then use VEP with GRCh38 to annotate variants. When I run pvacseq I get the error message below. However, I have noticed that the problem appears to be limited to inframe deletions (1-2% of total variants). When I delete these variants using grep -v <input_vcf> > output_vcf and then re-run, it works. Therefore I don't think it is actually a problem with the assembly used to annotate. I have attached a VEP-annotated vcf as an example.

**To Reproduce**
pvacseq run -e 8,9,10,11 --iedb-install-directory IEDB OX1072_patient_vep.vcf OX1072_patient HLA-A*02:01,HLA-B*18:01,HLA-B*44:02,HLA-C*05:01,HLA-C*07:01 NetMHCpan NetMHCIIpan pvactools_output

**Log Output**
```
ERROR: There was a mismatch between the actual wildtype amino acid sequence (ELGHPSARW) and the expected amino acid sequence (DWGTPALGG). Did you use the same reference build version for VEP that you used for creating the VCF?
```

**Output File**

**Expected behavior**

**Comment by susannasiebert** [comment]
The problem is with your VEP annotation because the reference bases of your variant don't match the Ensembl transcripts at that position. Unfortunately, there is nothing pVACseq can do to resolve this. Please note this section of our documentation for a more thorough explanation: https://pvactools.readthedocs.io/en/latest/pvacseq/errors.html#input-vcf-vep-annotation (scroll down for your information about your particular error). 

You might want to consider contacting VEP for more help with this issue.

**Comment by csweeney225** [comment]
Thank you. I will contact VEP to see if they can advise.
