### ISSUE TITLE
Create new vaccine selection report

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVACtools#485]
Mockup and rough R code are attached.  Key features:
- "binning" of peptides into predefined categories/tiers
- revision that exposes more data in a more interpretable manner

As discussed, step 1 is to create a simple TSV like this as a report, for import into excel or something.

Step 2 will be to create an interactive HTML/JS page that adds the following features (in order of priority):
1) color coding of cell backgrounds
2) highlighting of mutant peptides in red
3) checkboxes that allow peptides to be selected, and an "export" button that spits out a tsv with only the selected peptides. 
4) "pop-up" boxes that allow a user to drill down into the data.
  - the first priority would allow for clicking on the number of peptides, and show all passing peptides for that mutation (along with transcript id, mutation position highlighted, and ic50 scores)

[example_ranking.xlsx](https://github.com/griffithlab/pVACtools/files/4036905/example_ranking.xlsx)

[ranking.R.gz](https://github.com/griffithlab/pVACtools/files/4036909/ranking.R.gz)
(wouldn't allow me to attach an R file, so I gzipped it)

**Comment by malachig** [comment]
FYI, I am aware of at least two other ongoing efforts with partially overlapping goals.  Particularly for the visualization part.  Zach has been working on a Shiny app that does some of this for data from the HuMO project and Huiming has been working on a Shiny app that is meant to aid in selection of vaccine candidate in an immunotherapy tumor board setting.

**Comment by susannasiebert** [comment]
I think we should have a followup meeting to discuss the future of pVACviz. One thing discussed yesterday was to replace the existing server-client model with a step in the pipeline that would produce html pages for the reports that could then be loaded in a browser. This would be easier maintainable and more robust than the existing framework.

**Comment by malachig** [comment]
One thing for us to remember is that since this script goes back to the unfiltered all_epitopes file (which it must to get a sense of the collection of neoantigen candidates for each variant) ...  this means that it side steps a lot of what is happening in pVACseq run.  In a sense it deprecates much of what is happening in:

-  pvacseq binding_filter 
- pvacseq coverage_filter 
- pvacseq transcript_support_level_filter  
- pvacseq top_score_filter and 
- pvacseq generate_condensed_ranked_report

A lot of our decisions and thoughts about filtering, prioritization and interpretation are baked into these modules.  Thus bringing the concepts of building this new vaccine selection report into the fold may require us to revisit how these modules are organized and documented.  As well as how we recommend running a vaccine design pipeline to the uninitiated.

**Comment by susannasiebert** [comment]
From an earlier comment I made in the pvactools channel about how to parametrize the aggregate report

Existing thresholds to parameterize:
- Median WT Score (to determine anchor residues)
- Tumor RNA VAF * Gene Expression (Pass)
- Tumor RNA VAF * Gene Expression (Relaxed)
- Median MT Score (Pass)
- Median MT Score (Relaxed)
- top score metric? (median vs lowest)

Current hard filters that aren’t used in aggregate tiering:
- Fold Change
- Allele specific MT Score filtering (if we use this the allele-specific value could be used for pass and double it could be used for relaxed)
- Normal Depth
- Normal VAF
- Tumor RNA Depth
- Tumor DNA Depth
- Transcript Expression
- Transcript support level

Notes:
- In the tiering Tumor DNA VAF is compared to an estimate of the clonal VAF instead of a specific numeric threshold
- In the tiering Tumor RNA VAF and Gene Expression are not compared individually to specific numeric thresholds; instead their product is compared
- Should the relaxed MT Score threshold be a function of the pass MT Score threshold (e.g. double)?

**Comment by susannasiebert** [comment]
During today's meeting it was decided that the parameterization would be put off until version 2.1.

**Comment by susannasiebert** [comment]
Tracking for additional features will be done in separate issues (e.g. https://github.com/griffithlab/pVACtools/issues/606 and #633). Closing.
