### ISSUE TITLE
pVACfuse filtering out peptides (because of fusion position > peptide length?)

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/pVACtools#52]
This might be what you were talking about @susannasiebert in #49. I'm guessing this is what the code intended. However, this is limiting the neoantigen candidate results and we're still getting not getting anything with a median MT binding < 500. Is it necessary to filter these out? See this example:

Input: `/gscmnt/gc2142/griffithlab/yafeng/cwl_toil_runs/unstranded/paper_fusions/fusion_antigens_out/fusions.bedpe.annot.stripped`

Outdir:
`/gscmnt/gc2142/griffithlab/yafeng/cwl_toil_runs/pvacseq_output/hcc1395_fuse_paper_stripped/MHC_Class_I`

`sample.combined.parsed.tsv` only contains peptides from the first fusion in the input bedpe, which also happens to be the only line in which the fusion position <= length of peptide sequence.

**Comment by susannasiebert** [comment]
Yes. The position information that we need is where in the fusion peptide sequence the fusion occurs. We need this information in order to center the pvafuse 21-mer around that position. Since these cases have a fusion position > fusion peptide length, the code interprets this as the fusion occurring after end of the fusion peptide, which doesn't make any sense. 

I'm not sure what alternative you are suggesting. The only other option I can think of is to use the full fusion peptide sequence. In that case we still don't know where the fusion position is and, thus, we don't know where the novel sequence begins (for frameshifts) or which epitopes are novel (for inframe fusions).

**Comment by yang-yangfeng** [comment]
@susannasiebert - Jin helped me run integrate-neo with his own fasta/gene annotations and the results look like what you would expect. I think your previous assumptions about the bedpe were correct. The problem seems to have to do with my fasta file - thought not sure exactly what is causing the problem. In any case, I've run pvacfuse with the new bedpe and looks like we have some good candidates!
