### ISSUE TITLE
can generate_protein_fasta include more consequences like splice_donor, start_lost etc..

### ISSUE THREAD

**Issue by jeongmeani** [griffithlab/pVACtools#567]
Hi @susannasiebert 

i analysis WES data. and using pvacseq generate_protein_fasta, i would get peptide sequence of mutation.
but i want to include splice_donor, start_lost and other consequences.

so i open the script input_file_converter.py and fasta_generator.py.

in input_file_converter.py, i guess resolve_consequence function is target to be modified.
and FastaGenerator in fasta_generator.py also to be modifed.

but it seems like difficult. 

so can you give me hint?

especially  **FastaGenerator in fasta_generator.py**

Best Regards

Jeongmin

**Comment by susannasiebert** [comment]
Thanks for your interest in pVACtools. In regards to `start_lost` we purposely remove variants deleting the start codon as they won't result in a peptide sequence (since there is no start codon to indicate start of translation). Detecting splice variants (and other types of complex variants) and resolving their consequences is somewhat complex, as you've discovered yourself. While it is on our development roadmap, we do not currently have all the pieces in place needed to support it.  We welcome contributions from the community, and would be happy to take a look at a solution if you come up with one.
