### ISSUE TITLE
Mismatch between the actual wildtype amino acid sequence and the expected amino acid sequence

### ISSUE THREAD

**Issue by wenweiliang** [griffithlab/pVACtools#571]
* pvactools version: docker
* Python version: 3.6
* Operating System: Linux

**Describe the bug**
While pVACseq works well for half of our samples, the other half complained that a mismatch was detected between Wildtype amino acid sequence and the expected amino acid sequence. Since all the inputs have been processed identically by VEP, I am wondering what can we do to make pVACseq work for the remaining samples? A VCF for testing is attached. 

**To Reproduce**
```
docker run -v /path/2/data:/data -it griffithlab/pvactools
cd /data
pvacseq run test.vcf Test HLA-A*02:01,HLA-A*02:01,HLA-B*52:01,HLA-B*52:01,HLA-C*16:01,HLA-C*16:01 NetMHCpan output -e 8,9,10 -t 30 --iedb-install-directory /opt/idea
```

**Log Output**
```
ERROR: There was a mismatch between the actual wildtype amino acid sequence (QQQQHSNQTSNWSP) and the expected amino acid sequence (QQQQQQQQQQQQQQ). Did you use the same reference build version for VEP that you used for creating the VCF?
OrderedDict([('chromosome_name', 'chr4'), ('start', '140811063'), ('stop', '140811102'), ('reference', 'TTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGC'), ('variant', 'T'), ('gene_name', 'MAML3'), ('transcript_name', 'ENST00000398940'), ('transcript_support_level', 'NA'), ('amino_acid_change', 'QQQQQQQQQQQQQQ/Q'), ('codon_change', 'caGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAa/caa'), ('ensembl_gene_id', 'ENSG00000196782'), ('hgvsc', 'ENST00000398940.1:c.105_110del'), ('hgvsp', 'ENSP00000381913.1:p.Gln37_Gln38del'), ('wildtype_amino_acid_sequence', 'MSPAEQLKQMAAQQQQRAKLMQQKQQQQQQQQQQQQQQHSNQTSNWSPLGPPSSPYGAAFTAEKPNSPMMYPQAFNNQNPIVPPMANNLQKTTMNNYLPQNHMNMINQQPNNLGTNSLNKQHNILTYGNTKPLTHFNADLSQRMTPPVANPNKNPLMPYIQQQQQQQQQQQQQQQQQQPPPPQLQAPRAHLSEDQKRLLLMKQKGVMNQPMAYAALPSHGQVSVKVTHSSSSSCGAFDCRCVMFYKSTVVGSNCLQKTSLHPQVVARFGVFFFHFS'), ('downstream_amino_acid_sequence', ''), ('fusion_amino_acid_sequence', ''), ('variant_type', 'inframe_del'), ('protein_position', '35-37'), ('transcript_expression', 'NA'), ('gene_expression', 'NA'), ('normal_depth', 'NA'), ('normal_vaf', 'NA'), ('tdna_depth', '415'), ('tdna_vaf', '0.40481927710843374'), ('trna_depth', 'NA'), ('trna_vaf', 'NA'), ('index', '59.MAML3.ENST00000398940.inframe_del.35-37QQQQQQQQQQQQQQ/Q'), ('protein_length_change', '')]) 
```

**Output File**
[test.vcf.zip](https://github.com/griffithlab/pVACtools/files/4990496/test.vcf.zip)

**Expected behavior**
Perform prediction based on frameshift mutations

**Comment by susannasiebert** [comment]
I'm sorry you're encountering this error. This is, unfortunately, one of those errors that can't be resolved by pVACseq since it is caused be a fundamental mismatch between the reference used while creating the VCF and the reference used by Ensembl/VEP. Have you tried any of the suggestions mentioned on the [Common Errors](https://pvactools.readthedocs.io/en/latest/pvacseq/errors.html) page in our documentation? The section for this error is almost all of the way at the bottom of the page. If none of those suggestions work the last resort would be to remove the offending variants from the VCF.

**Comment by wenweiliang** [comment]
Hi @susannasiebert, 
Yes I have tried the ways in common errors page. Since pVACseq works well for half of our samples, I am wondering why VEP annotate differently for particular variants... Yes, I will remove the variants from VCF. Thanks!

**Comment by susannasiebert** [comment]
The reason is that some of the reference nucleotides in the reference used for your VCF during alignment and variant calling are different from the ones in the Ensembl reference/transcript nucleotide sequence. Thus the REF field of a variant and such a position is different than the Ensembl transcript nucleotide at the same position. This results in the mutant amino acid in the Amino_acids VEP annotation being different from the amino acid of the transcript protein sequence as predicted by the Wildtype plugin. The Amino_acids VEP annotation is based on the reference and alternate nucleotides of the variant while the WildtypeProtein prediction is based on the Ensembl transcript nucleotide sequence.

This points to a fundamental disagreement between the reference that was used during alignment and variant calling and the Ensembl reference. This mismatch cannot be resolved by pVACseq, which is why this error is fatal.

**Comment by susannasiebert** [comment]
I am closing this issue since there has been no more activity but do feel free to reopen this issue if you're still having problems.
