### ISSUE TITLE
I wonder why pVACfuse selects epitope (frameshift_fusion) upstream of a splice-site

### ISSUE THREAD

**Issue by ShahiRB** [griffithlab/pVACtools#577]
Hi Susanna,

**pvactools-1.5.9 ;**

Epitope selected/prioritized is : **LPALGLLLW** (PSCA-CCDC124/**ENST00000301258-ENST00000445755**)

Whereas the fasta file generated by AGFusion/1.2 looks like this.

\>ENSP00000301258-ENSP00000408730 length=122, kD: 13.202247499999977, transcripts: **ENST00000301258-ENST00000445755**, genes: PSCA-CCDC124, effect: out-of-frame
MAGLALQPGTALLCYSCKAQVSNEDCLQVENCTQLGEQCWTARIRAVGLLTVISKGCSLNCVDDSQDYYVGKKNITCCDTDLCNASGAHALQPAAAILAL**LPALGLLLW**G*PRAIWRCRWRRT

As it is out-of-frame fusion, isn't it the epitope selected/prioritized should have peptide sequence either with splice site or sequence downstream of the splice site?

Regards,
Rajendra

**Comment by susannasiebert** [comment]
Hi Rajendra,

I'm sorry that you are running into this issue. We are aware that this a problem in current versions of pVACtools and it is scheduled to be fixed in version 2.0. Please follow https://github.com/griffithlab/pVACtools/issues/523, where we are tracking this problem. I'm closing your issue in lieu of #523.

Susanna
