### ISSUE TITLE
vcf-readcount-annotator only annotates first variant for indel

### ISSUE THREAD

**Issue by nickhir** [griffithlab/pVACtools#604]
Hello,
I also posted this issue [here](https://github.com/griffithlab/VAtools/issues/42), but I wasn't sure if this repository was still actively maintained, and because VAtools is a essential part of pVACtools, I thought I would also ask it here. Please feel free to remove this issue if it is out of place!

Regarding my problem:
I am trying to annotate my indel VCF as part of preprocessing for pVAC.
I followed [this guide](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/readcounts.html) and everything works without an error, but when examining the final indel VCF file, I realized that only the first variant is actually annotated with the DP, AF and AD.

I have attached the output VCF file and the readcount file from the bam-readout.

Interestingly, for the snv VCF file, everything worked perfectly and everything got annotated.

Do you have an idea what might have gone wrong?

[indel.zip](https://github.com/griffithlab/pVACtools/files/5481461/indel.zip)
Cheers!

**Comment by susannasiebert** [comment]
I apologize, I did see your issue but haven't had time yet to look into it. I will work on it today.

**Comment by susannasiebert** [comment]
Ok, digging into this, the variants that are annotated with 0 readcounts are all deletions. This is because the bam-readcount file does not contain an entry for the deleted ref base. E.g., for `3	171321022	AC	A` the annotator is looking for a `-C` entry in the bam readcount list of alts. This is similar to how there is a `+T` entry for the `2	26676206	G	GT` insertion variant. This might be a problem with bam-readcount or it could simply be that there aren't any readcounts covering this alt. All of the reads for the deletion variants are getting counted for the ref base and even for the insertion variant, only 2 reads covered the insertion (the rest are ref). Are the bams used NORMAL bams by any chance? Can you confirm that you ran bam-readcount in insertion-centric mode for these variants?

**Comment by nickhir** [comment]
Hi, 
Thank you very much for taking the time!

I see what the problem is now... "unfortunately" the BAM I am running bam-readcount on is the tumor bam. And I also made sure that I ran it in insertion-centric mode. 

However, I think I might have made a mistake when creating the  `site-list` for the decomposed indel vcf. 
Specifically, my `site-list` looks somthing like this:
```
2	26676206	26676206
3	171321022	171321022
6	151672915	151672915
20	35177622	35177622
20	35177628	35177628
21	30337044	30337044
X	3559899	3559899
X	123515076	123515076
```
Should the interval (start to stop) span the whole indel?

**Comment by susannasiebert** [comment]
That is a good point. I'm not super familiar with the exact rules. We made a helper script in the https://github.com/genome/docker-bam_readcount_helper-cwl/tree/1.1.1 repo that takes care of all these steps. The accompanying docker container is at `mgibio/bam_readcount_helper-cwl`. I apologize but our documentation for this script is lacking because we use it internally with our CWL pipelines. But you can also use the script/container directly. I believe the positional arguments to the script are `vcf sample reference_fasta bam output_file_prefix output_directory`.

**Comment by nickhir** [comment]
Thank you very much for pointing me to that python script! 
I adjusted a few things and now the results make a lot more sense.
Thanks again for all your help!
