### ISSUE TITLE
latest version of iedb

### ISSUE THREAD

**Issue by laurie-tonon** [griffithlab/pVACtools#608]
Hello,

Is it possible to use pVACseq with the latest version of IEDB tools? This version use the latest versions of NetMHC & co with their predictions on eluted ligands and it would be very nice to use it with the rest of the pipeline.
Is it something that you plan to add?

Thanks a lot

**Comment by susannasiebert** [comment]
We will be adding support for the latest version of IEDB in the upcoming release 2.0.0 which should be out at the end of the month or December at the latest.

**Comment by laurie-tonon** [comment]
Excellent news, I look forward for this new version.
Thanks a lot

**Comment by susannasiebert** [comment]
The new version of pVACtools (2.0) has just been released, which is compatible with IEDB 3.1 and above. The 2.0.0 version of the docker container comes with that version of IEDB pre-installed. Please note that you will need to re-annotate your VCF since there have been other, unrelated, changes to the pVACseq workflow that make existing versions of your VEP-annotated VCFs incompatible. Please see the [release notes](https://pvactools.readthedocs.io/en/latest/releases/2_0.html#breaking-changes) and [VEP instructions](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/vep.html#vep) for more information.

Please also note, that eluted data for NetMHCpan is not currently reported by pVACtools but we are planning on adding this feature with the next release. Please feel free to follow https://github.com/griffithlab/pVACtools/issues/619 to keep up-to-date with the development for this feature.
