### ISSUE TITLE
Complex variant or MNP will be skipped: 1	65311116	GC	CT in bam_readcount_helper.py

### ISSUE THREAD

**Issue by 2236529177** [griffithlab/pVACtools#616]
Dear professor,
thanks in advance, mnp and complex variant is important, if can not be added depth, it maybe not well evaluated in neoantigen prediction,
thanks a lot
![image](https://user-images.githubusercontent.com/25199946/101738829-b0136800-3b01-11eb-9a0e-4c29eb44a5ca.png)

**Comment by susannasiebert** [comment]
Unfortunately, readcounts for MNPs are exceedingly complicated. For example, if an MNP spans 3 bases, all with different depths, which one do we report? As a stopgap you could backfill the VCF with the readcounts reported from one of the original variant callers after you run the vcf-readcount-annotator.

Either way, this issue is not appropriate for the pVACtools repository since this is not a problem with pVACtools itself, i.e. pVACseq only reports the readcounts that are already available in the VCF. As such, I will close this issue. You might want to consider making an issue in the bam-readcount repository (https://github.com/genome/bam-readcount), although that tool has not seen much active maintenance.

If you find a different tool that reports readcounts for all types of variants, including complex variants, you are welcome to make an issue in the VAtools repository (https://github.com/griffithlab/VAtools) so that we can add support for it. To our knowledge no such tool currently exists.

Lastly, you are not required to use bam-readcount and can run pVACseq with the readcounts as reported by the variant callers or without readcounts altogether.
