### ISSUE TITLE
pthread_create failed: Resource temporarily unavailable.

### ISSUE THREAD

**Issue by worker000000** [griffithlab/pVACtools#618]
runtime/cgo: runtime/cgo: pthread_create failed: Resource temporarily unavailable.
have you ever met this? it seems pvactools will take much resource, I set -t 16. and run four samples in parallele.
do you have some suggestions about this, if run in parallele can not dealed wel, it is also a big problem. I also see the default is 1, but I see even I set 16, the used cpu ismore than 16(there is no other job), so does it mean the prediction tools used more resource than used?

**-t N_THREADS, --n-threads N_THREADS
                        Number of threads to use for parallelizing peptide-MHC
                        binding prediction calls. (default: 1)**

my computer ha**s 400G memory and 64cpu**

thanks a lot

**Comment by worker000000** [comment]
is there any response about this?
thanks a lot

**Comment by susannasiebert** [comment]
Please try a smaller number of threads or a smaller number of parallel pVACseq runs.

**Comment by malachig** [comment]
Or use a cluster or cloud compute platform for this kind of work.  It is possible that even with 400G on a box, run 4 x 16 threads at once is still exceeding available memory and this in turn is causing a failure to allocate more threads.  We and others have used pvacseq successfully to process many 1000s of tumor samples.  In general, a more cost effective strategy is to break the work into smaller pieces and submit each to a cluster using modest resources for each job.  Rather than trying to run a few very large jobs on a single computer.
