### ISSUE TITLE
Add standalone commands to add stability prediction and proteome similarity to any pVACtools result file

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#657]
* pvactools version: 2.0.1

Hi I was just wondering if there is any particular reason that the stability and proteome similarity feature is only restricted on the filtered result? Is it because of the overhead? As the filtered list only return one epitope per variant, is there a way we can get the stability and similarity scores for other epitopes of the same variant as well within the pvacseq tool?

**Comment by susannasiebert** [comment]
You are correct that this is because of the overhead for these functions as they rely on API calls, which are usually rate-limited by the respective tool. We can add standalone commands to run these tools on a pVACseq output file (or a subset of one) with the caveat that you might run into errors when submitting files with many epitopes. I will add this issue to the 2.1 milestone.

**Comment by susannasiebert** [comment]
The tools we want to be able to run as a standalone command:
- reference proteome similarity
- cleavage site predictions
- stability predictions
