### ISSUE TITLE
new VEP plugin

### ISSUE THREAD

**Issue by oldguyeric** [griffithlab/pVACtools#678]
Your Wildtype and Frameshift plug-ins are very useful. Have you considered also making a plug-in for mutations on splice site regions? 

Thanks

**Comment by malachig** [comment]
Yes, we have actually thought of this a bit.  Only very briefly in the context of a VEP plug-in, but more generally we are working to support neoantigens from isoforms. 

One strategy could be to simply focus those somatic variants that are annotated by VEP as splice variants or splice region variants.  One could then predict the impact on splicing and infer the impact on the ORF.  

However, without being guided by RNA-seq data, it can be difficult to accurately predict the impact of even the most obvious splice variants.  For example, a variant that directly disrupts an acceptor site can lead to: (a) skipping of exon, (b) use of an alternative upstream or downstream acceptor site, (c) a combination of both, (d) other less common alternative splicing patterns.

What I would like to do is combine predictions from our tool RegTools with pVACtools to tackle this problem.  At a high level we would use RegTools to mine the RNA-seq data for specific alternative splicing events actually observed to be expressed that appear to be caused by somatic splice variants.  Then using this knowledge, guide the prediction of alternative ORFs.  At that point we could encode them into a VCF (perhaps using a VEP plug-in that consumed this supplementary information).  Then pVACtools could be updated to utilize these annotation in the VCF to predict neoantigens arising from tumor specific alternative isoforms driven by somatic cis-regulatory splice variants.

I would like to leave this issue open while we think about this further.

**Comment by oldguyeric** [comment]
Thank you for the quick reply. I was thinking more regarding somatic variants that are annotated by VEP as splice variants or splice region variants that is why I thought of a plug-in but as you mentioned it is difficult to predict their impact without RNA-Seq.

Thanks for the consideration anyway. Cheers
