### ISSUE TITLE
unauthorized: authentication required of docker pull

### ISSUE THREAD

**Issue by worker000000** [griffithlab/pVACtools#704]
Thanks in advance
I run the same command in different server, but different stout, one even output unauthorized: authentication required, why this happen, will it affect the use of IEDB
![image](https://user-images.githubusercontent.com/25199946/133889922-7016116e-6cd4-4865-bba1-696883c6dd7f.png)
<>
![image](https://user-images.githubusercontent.com/25199946/133889936-29ebb70d-7b71-4cda-b87b-192f1ab9d3b5.png)

**Comment by susannasiebert** [comment]
I haven't encountered this error before but I don't think you would be able to run pVACtools since it wasn't able to successfully pull the image. I found this issue: https://github.com/docker/hub-feedback/issues/1484. Please try change suggested in this comment: https://github.com/docker/hub-feedback/issues/1484#issuecomment-471531227 and restart docker.
