### ISSUE TITLE
use_2to3 and setuptools 58+ problem

### ISSUE THREAD

**Issue by Stikus** [griffithlab/pVACtools#712]
Hello.
`use_2to3` support was removed in `setuptools 58` [changelog](https://setuptools.pypa.io/en/latest/history.html#v58-0-0)

`pVACtools` dependency `PyVCF` still have it ([PR about removing](https://github.com/jamescasbon/PyVCF/pull/331)).

We should:

1. Choose another dependency (maybe https://github.com/brentp/cyvcf2)
2. Choose patched version from PR or something similar
3. Pin `setuptools` version, but this is MAJOR problem for all future releases.

**Comment by Stikus** [comment]
Similar problem for [pysam](https://github.com/pysam-developers/pysam/commit/f31f6dc5f5876957bf9bb1eb393e3344d3e9768b).

Maybe another packages - a lot of packages still have `use_2to3`.  
Here are some interesting workarounds: https://github.com/pypa/setuptools/issues/2788

**Comment by susannasiebert** [comment]
I will look into switching to a different vcf parsing library. I've used [VCFPy](https://pypi.org/project/vcfpy/) successfully in other projects so that's what I would start with.

For pysam, since we're not pinning a version, having the change you linked released should be sufficient. Some of our dependencies might pin pysam but that would be up to them to update to a newer version.

**Comment by Stikus** [comment]
`pysam` just released fixed release: https://github.com/pysam-developers/pysam/releases/tag/v0.17.0 FYI

Will wait for `PyVCF` replacement. Should we use `setuptools<58` before you implement it?

**Comment by susannasiebert** [comment]
Yes, you will need to use an older setuptools version. Alternatively, you can use the existing docker container (griffithlab/pvactools) to get around any installation problems.

**Comment by biolxy** [comment]
```
pip install setuptools==57.5.0 
```

**Comment by Stikus** [comment]
Looks like issue should be closed, but something went wrong.
