### ISSUE TITLE
pvacseq pcroess become Z 

### ISSUE THREAD

**Issue by asmlgkj** [griffithlab/pVACtools#722]
thnanks a lot for the kind help
<br>

latest docker pvacseq

**Describe the bug**
I ran pvacseq, but it does not throw any error , but the pocess in ps aux become Z

**To Reproduce**
docker run --rm --user `id -u`:`id -g` -v $4:/data docker.io/griffithlab/pvactools pvacseq run /data/$3 $1 ${content_hla} NetMHCpan /data/pvacseq -e1 8,9,10,11  --iedb-install-directory /opt/iedb  -t 4 --tdna-vaf 0.01 --normal-sample-name $1_N -k --downstream-sequence-length 1000 -c 1 --exclude-NAs  --netmhc-stab  --net-chop-method cterm
<br>
this is the input.yaml
[inputs.zip](https://github.com/griffithlab/pVACtools/files/7374416/inputs.zip)

this is part of the tmp content? it never generate new files after timr 20:44, but the process does not stop until 23:00
![image](https://user-images.githubusercontent.com/50854682/137937086-1a4be74f-08c6-43d8-beb9-3c76965150aa.png)

<br>

<br>
**Expected behavior**
expect it can end normally

**Comment by asmlgkj** [comment]
> Can you define what you mean by "immunogenicity"? There are many measures related to that concept, several of which are provided by the pvactools output.

immunogenicity is something about the neoantigen Peptide to cause immunity, to simulate the  immune system

**Comment by asmlgkj** [comment]
> Can you please provide some more information about the pVACseq behavior. Does it error out eventually or hang indefinitely? What's the stdout from the pVACseq run?

thanks a lot
<br>
I have uploaded the log , vcf , command,
is there any other you want, can you tell me, I will  upload if you tell me

**Comment by asmlgkj** [comment]
thanks a lot
I delete the -t 4
but it seems also uspending , you can see the status is S or Sl, not R, but my computer is  a lot resourse left.
![image](https://user-images.githubusercontent.com/50854682/138009652-e2b579d3-1f0a-46a6-9846-5602dbad42cc.png)

<>
resource left
![image](https://user-images.githubusercontent.com/50854682/138009778-9c52c52a-9dbf-48d3-88d7-770fa7ec06f6.png)

**Comment by asmlgkj** [comment]
I run the shell script 
it shows it suspends here.
<br>
<br>
![image](https://user-images.githubusercontent.com/50854682/138018871-ae0a3ca6-e5ed-4cde-b135-31b86b86d82b.png)

**Comment by asmlgkj** [comment]
frameshift_variant transcript does not contain a FrameshiftSequence. Skipping.
<br>
![image](https://user-images.githubusercontent.com/50854682/138019057-99441a1e-e079-40cb-853d-de1fb581a7b9.png)

**Comment by asmlgkj** [comment]
mine is much resource than you.
CentOS Linux release 7.9.2009 (Core)
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
500G memory
120T storge

**Comment by asmlgkj** [comment]
though I do not run other pacseq jobs at the same time.
but I need to do it in the following time because I need to parallel run many samples if the process run smoothly?

**Comment by susannasiebert** [comment]
Gotcha, so that determination is a very complex, context-specific, and doesn't have one "right" answer, unfortunately. There are a lot of criteria to consider to determine whether an epitope is a good candidate or not and our understanding of this problem space is still evolving. In practice the pVACseq doesn't report a single metric that would reflect this and the results are usually discussed extensively in tumor board settings to determine the best candidates from all of the different metrics that pVACseq provides.

The binding affinity (Median MT Seq) is one thing you need to look at although some prefer the percentile (when it's available - not all predictor report it). Different HLA alleles have different binding affinity cutoffs that make an epitope a good binder for that allele. 

You also need to check on things like VAF, coverage, and expression to make sure that the variant has a lot of read support and is expressed in your patient and to determine which transcript is the one that your patient has. The position of the mutation on the epitope is also important to see whether the mutation is in an anchor position that would result in the mutated amino acid not actually being presented.

You can look at the filtered file to see all of the epitope that pass our stringent filtering criteria. The aggregate report has information about all of the variants and a tier that indicates why it didn't pass our filters.

The filtered file is supposed to be sorted by the Median MT Score but like you discovered in #726, this is currently not working correctly.

**Comment by asmlgkj** [comment]
Thanks a  lot.
so here to confirm again, the default output is the best order as far as the knowledge
