### ISSUE TITLE
Filtered and aggregate report interpretation

### ISSUE THREAD

**Issue by rbowenj** [griffithlab/pVACtools#724]
Hi,

Could you please clarify how the `all_epitopes.aggregated.tsv` and `filtered.tsv` reports relate to one another?
From the documentation I can tell that they are both generated from the `all_epitopes.tsv`, but the aggregated report contains vaccine suitability tiers, which the filtered report doesn't. 

My understanding was that the filtered report contained a top scoring peptide for each variant which passed all pVACtools filters, and therefore contained the info necessary to judge peptide suitability for vaccines. How does the aggregated report (with its tiers) fit into this, given it contains a different set of peptides to the filtered report?

Thanks!

**Comment by Gxyrrr** [comment]
I applied the default filtering conditions to the all_epitopes.aggregated.tsv file, but the result differs by 1 or 2 variants compared to the filtered.tsvall_epitopes.tsv file. Is this a normal situation?

**Comment by susannasiebert** [comment]
@Gxyrrr do you have a specific example I could look at? It should be rare but it's our goal to minimize these cases so I'd like to have a look at what might've caused the discrepancy.

**Comment by Gxyrrr** [comment]
I sincerely apologize for the late response due to the time difference. I greatly appreciate your help.
This is my original file, the command I ran, and the MHCI result file. The filtering conditions I applied to `all_epitopes.aggregated.tsv` were `tsl=1`, `DNA.vaf>=0.25`, `RNA.Expr>=1`, and `IC50.MT<=500`. However, the results I obtained are different from those in `filtered.tsv`.
[files.zip](https://github.com/user-attachments/files/16914105/files.zip)
