### ISSUE TITLE
pVACseq fails to generate predicted epitopes when using NetMHC

### ISSUE THREAD

**Issue by yzhan360** [griffithlab/pVACtools#741]
Hi, I am testing pVACseq workflows and first of all thanks for your great work!
I have successfully generated all_epitopes.tsv and the filtered.tsv using mhcflurry. But when using NetMHC, I only got <sample_name>.tsv_<chunks>, <sample_name>.tsv and <sample_name>.fasta. There is not a list of all predicted epitopes. 
I checked the log files. When using NetMHC, the workflow have parsed prediction files but did not combine Parsed Prediction Files. No error messages showed up. 
Could you provide some idea on what happened or what else I should double check? Looking forward to your thoughts.

Thanks, Yan

**Comment by susannasiebert** [comment]
@yzhan360 I'm sorry you're encountering problems with getting a successful pVACseq run. Can you please post the stdout from your run?

Also, if you could provide additional information about your compute environment, that would be helpful. Do you have a standalone installation of pVACseq or are you using the docker container? Do you run it on a compute cluster or an a local machine?

**Comment by yzhan360** [comment]
Thanks for your quick response!
Here is my stdout when using NetMHC
[NetMHC_run2.log](https://github.com/griffithlab/pVACtools/files/7652432/NetMHC_run2.log)
here is the stdout when using MHCflurry
[MHCflurry_run2.log](https://github.com/griffithlab/pVACtools/files/7652453/MHCflurry_run2.log)
and here is the computer environment
[nghead_env.txt](https://github.com/griffithlab/pVACtools/files/7652433/nghead_env.txt)
I installed pVACseq using the docker container: Docker version 19.03.15, build 99e3ed8

**Comment by susannasiebert** [comment]
Hm, I don't see anything obvious here. Usually these sort of problems occur because the system is running out of resources (e.g. memory, hitting a max processes limit). I will need more information to debug this error:

- I assume you are using the official griffithlab/pvactools docker image? Which version are you using?
- What's the full pvacseq command you are trying to run?
- Please attach the input VCF file
- Please attach the output directory for your run
- Are you running multiple pvacseq runs at the same time on the same machine?
- Did your NetMHC run exit or is it hanging?

Please note that today is my last work day before I leave on vacation until the end of the year so I won't be able to further assist with this problem until I return. Some things you might want to try in the meantime:
- If you're not using the latest pVACtools version (2.0.5), upgrade to the latest one
- If you are running with the -t option, try running without it
- If you are running multiple pvacseq runs at the same time, try running them sequentially
- Reduce the --downstream-sequence-length to 100
- Subset your input VCF to 1000 variants per VCF and run each subsetted VCF separately

**Comment by susannasiebert** [comment]
@yzhan360 Have you had a chance to retry your pVACseq run with any of the recommendations above?

**Comment by yzhan360** [comment]
Hi, Susanna! Happy New Year! Thanks for following up. I have tried running without -t and reducing the --downstream-sequence-length to 100. It works! I got the all_epitopes and filterd.tsv! Thanks so much! 
My question is that what's the difference between --downstream-sequence-length 100 and 1000. Do I get a smaller amount of prediction when I use 100?

**Comment by susannasiebert** [comment]
Correct. With a length of 100 you basically only get the first 100 amino acids after the frameshift mutation. For most frameshift mutations that isn't a problem as the tail is much shorter but some mutations can get quite long depending on when the frameshifted sequence codes for a stop. Reducing the downstream sequence length will leave out any potential neoepitopes after the cutoff. This is pretty rare though.

**Comment by yzhan360** [comment]
Thanks a lot for your prompt response!

**Comment by susannasiebert** [comment]
You're welcome. I'm resolving this issue but do feel free to reopen it or make a new one if you run into any additional trouble.
