### ISSUE TITLE
How to use RNA VAF/coverage filter + Creating a phased VCF not worked

### ISSUE THREAD

**Issue by agnesfoi** [griffithlab/pVACtools#749]
Hi, we are testing pVACseq workflows with WES+ RNA seq data and have several questions.

- For the pvacseq input file preparation step, we have successfully generated annoted WES_input.vcf (WES) with coverage (WES) and expression (RNA) informations, etc., 'pvacseq run
/WES_input.vcf' worked perfectly. However, I did not find how to filter results by RNA coverage or VAF, since output files (sample_all_epitopes.tsv) have NA in 'Tumor RNA Depth' and 'Tumor RNA VAF' columns, how to apply RNA filter? Is there anyway to add RNA coverage info to the WES VCF? Or could you provide some suggestions?

- For the pvacseq Creating a phased VCF step, when we use GATK3.6 ,GATK3.8 and GATK4 to create a phased VCF of proximal variants, I have got this error: 'Could not find walker with name: ReadBackedPhasing? Would you know what happended? What is the best version of GATK we should use?

- We have found this link in your article https://github.com/genome/analysis-workflows/blob/master/definitions/pipelines/immuno.cwl. This is a perfect idea of creating workflow starting from rawdata. I would like to ask by any chance do you have already a complete pipeline (in python or in R) which started from sequencing raw data? It will be very helpful for us!

We appreciate your help, thanks in advance!

**Comment by susannasiebert** [comment]
Thank you for your interest in pVACtools. I'll attempt to answer your question in order:

- Did you follow the steps outlined [here](https://pvactools.readthedocs.io/en/staging/pvacseq/input_file_prep/readcounts.html) for annotating your VCF with readcount information? In order to add RNA VAF and depth you will need to run bam-readcount on your RNAseq BAMs and run the vcf-readcount-annotator with the `RNA` option.
-  We've been using GATK3.6 to run this tool. I believe it has been removed in subsequent versions. I'm not sure why GATK3.6 would throw that error for you. You would need to contact the GATK team for further troubleshooting. We've been successfully using the mgibio/gatk-cwl:3.6.0 Docker container to run this step so you might want to see if that works for you.
- Unfortunately, we don't have a python or R version of this pipeline and we don't have any immediate plans of adding them but we are always happy to incorporate community contributions if you were to try and make one.

**Comment by breezetown** [comment]
Hi,for the same sample, we got one somatic vcf file from  WES data (tumor and normal WES data) and one  vcf form the RNA-seq data.But how to use these two VCF file as the input file? In other words,how to integrate these two vcf files ?

**Comment by susannasiebert** [comment]
pVACtools only takes in a somatic VCF file. For RNA readcounts, it inspects the RAD, RAF, RDP per-sample fields in the somatic VCF. Our established procedure for incorporating these fields into a somatic VCF is the one outlines above (using bam-readcount on the tumor RNA BAMs followed by running the vcf-readcount-annotator). We don't have an established procedure for annotating your somatic VCF with RNA readcounts from and RNAseq VCF. You could try to do so manually using a VCF parser like VCFpy.
