### ISSUE TITLE
Why have some of my epitopes been filtered out even though the Best MT Score is below 500?

### ISSUE THREAD

**Issue by Hagay-Ladany** [griffithlab/pVACtools#835]
Hi,
I am using pVACseq 2.0.1 with only one algorithm (netMHCpan) so the "Median MT Score" equals to "Best MT Score".
Even though, I still don't get all the below 500 epitopes in the filtered.tsv file.
when I run "pvacseq binding_filter" on default settings I will get many more results.
Are there any additional filters applied?
Thanks

**Comment by susannasiebert** [comment]
Please see our documentation on the output files [here](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filters-applied-to-the-filtered-tsv-file) for a list of filters applied in pVACseq. What you are seeing is probably related to the top score filter only keeping the best epitope for each variant-transcript combination.

**Comment by Hagay-Ladany** [comment]
Thank you for the answer.
I scanned the frameshift peptides for binding against ~1000 HLAs (scanning 4 HLAs in each run).
I notice that for each mutation the filtered.tsv shows only the best binding epitope regardless of the different HLAs.

**Comment by susannasiebert** [comment]
> I notice that for each mutation the filtered.tsv shows only the best binding epitope regardless of the different HLAs.

That is intentional with the top score filter as it doesn't really matter much in practice, which HLA allele the best binder binds to. If the distinction is important for your use case, you could run each HLA allele separately or filter the all_epitopes file manually. You might also find the aggregate report of interest as it will show you how many peptides for each variant bound well to which HLA allele - although you won't be able to see the exact peptides for each. You would need to run pVACtools 3.0 and use pVACview to view this information.
