### ISSUE TITLE
Several KeyErrors

### ISSUE THREAD

**Issue by ysbioinfo** [griffithlab/pVACtools#982]
### Installation Type

Standalone

### pVACtools Version / Docker Image

3.1.3

### Python Version

3.8.3

### Operating System

Centos7

### Describe the bug

Hi pVACtools developers,
I encountered several different KeyErrors when I ran pVACTools on a batch of samples. I have searched "KeyError" on Github to see  if any previous issue can help me, like #970 and #978 . I can make sure that: (1) I am using the latest version of pVACtools (3.1.3) (2) I have removed all files in the output folder before I ran pVACtools, but these errors still pop up.

Since the KeyError for different samples are different, I summarized all of them here: 
[error_summary.txt](https://github.com/griffithlab/pVACtools/files/11754712/error_summary.txt)
.
It includes the "Error line" and "10 lines above the Error line" (using `grep -n -B 10 "Error" * | grep -v "^--" > error_summary.txt`). As you can see, there are in total 3 types of KeyErrors coming from 3 code lines of pVACtools:
(1) `if protein_identifiers_from_label[protein_label] is not None:`
(2) `wt_result = wt_results[match_position]`
(3) `result['corresponding_wt_{}'.format(metric)] = result['wt_{}s'.format(metric)][best_mt_value_method]`

I guess it might be caused by some strange mutations in my VCF file. So I also selected 4 of my VCF files for you to check (see below). 

In addition, I want to know that, why I always saw "IEDB Retry 1 of 5, IEDB Retry 2 of 5". I do not understand what it means, because my server is not connected to the internet and I do not use IEDB prediction workflow. Is it an error?

Thanks in advance!

Yours
Yang

### How to reproduce this bug

```Shell
pvacseq run P007020_004T.vcf \
                    P007020_004T \
                    HLA-A*02:01,HLA-A*03:01,HLA-B*35:01,HLA-B*35:01,HLA-C*03:02,HLA-C*04:01 \
                    NetMHCpan MHCflurry \
                    out \
                    -e1 8,9,10,11 \
                    --netmhc-stab
```

### Input files

I put 4 vcf files here, their corresponding KeyErrors are:
P007020_004T: `if protein_identifiers_from_label[protein_label] is not None:     KeyError: 46`
P032015_002T: `if protein_identifiers_from_label[protein_label] is not None:     KeyError: 39`
P040004_001T: `wt_result = wt_results[match_position]    KeyError: 11`
P081031_005T: `result['corresponding_wt_{}'.format(metric)] = result['wt_{}s'.format(metric)][best_mt_value_method]    KeyError: 'MHCflurry'`

Although it is only a part of my cohort, I think these files are representative enough. 

[pvactools_debug.zip](https://github.com/griffithlab/pVACtools/files/11754668/pvactools_debug.zip)

### Log output

The logout file has been uploaded above

**Comment by susannasiebert** [comment]
I believe these errors are related to your server not being connected to the internet. pVACtools uses the IEDB API for certain prediction algorithms, including NetMHCpan, so that process will make web requests and when those fail you will see those retry messages. We will need to make changes to the codebase so that if there is non internet connection pVACseq would still make predictions for non-IEDB algorithms like MHCflurry or error out if you try to use features that require an internet connection.

For your setup, you will need to install the IEDB software (see https://pvactools.readthedocs.io/en/latest/install.html#installing-iedb-binding-prediction-tools-strongly-recommended) and use the `--iedb-install-directory` parameter. You will also not be able to use the features like stability and cleavage site predictions since those also require an internet connection.

**Comment by ysbioinfo** [comment]
Hi Susanna,
Thanks for your prompt reply! Could you confirm my understanding is correct, that is, all of these KeyErrors are caused by my internet connection?
If that's true, I have two follow-up questions:
1. If I install IEDB software locally and use the `--iedb-install-directory`, which algorithm could I use for prediction? I know that NetMHCStabpan is an IEDB software,  but from what you said, it seems NetMHCStabpan is not enabled even after installing IEDB locally. Could you please list all algorithms that can be run locally?
2. Since the internet connection of my computing node is very unstable, I'm thinking if there is any workaround that can solve this problem thoroughly. For example, can I use pVACseq only for annotating and generating a "mutation--mutated_protein--mutated_short_peptide" table, and then predict the MHC binding of these peptides by myself (because I have already installed tools like NetMHCpan, MHCflurry etc locally)? After the prediction, I can match the "mutated_short_peptide--BA" table with the "mutation--mutated_protein--mutated_short_peptide" table, and get an output similar with pVACseq.
Can I use pVACseq to achieve this goal and which intermediate file should I use? Look forward to your advice.

Thanks
Yang

**Comment by susannasiebert** [comment]
You can find a list of supported algorithms on [this page of the documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/features.html) as well as by running `pvactools run -h`. NetMHCstabpan is a special case. It's not a "prediction algorithm" in the traditional sense since it doesn't predict binding affinity or elution. The IEDB implementation doesn't return all of the columns we desire for stability predictions, which is why we use the API even if IEDB is installed locally. However, this step is optional so you are ok without an internet connection as long as you don't enable it (which you didn't in your original pvacseq run command). The other feature that won't work without an internet connection is NetChop cleavage site predictions. Additionally, if you want to run the reference proteome similarity, you would need to install BLASTp standalone.

If you'd rather run all the prediction tools yourself you can generate a matched mutant/wildtype fasta file for your variants using the `pvacseq generate_protein_fasta` command ([documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/features.html)). However, you will miss out on a lot of pVACseq features like filtering, the aggregate report, etc. I honestly think that this is necessary once you have IEDB installed. If you desire stability and cleavage site predictions, you can run those standalone on the pVACseq final outputs.

**Comment by ysbioinfo** [comment]
Hi Susanna,
Thanks so much for your detailed explanation and valuable suggestions. I'll take a try following your advice.

Yang
